# Generated by Django 3.2 on 2022-05-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shoe_size',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
